import { Eye, EyeOff } from 'lucide-react'
import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/Button'

export function Auth() {
  const { t } = useTranslation(); const navigate = useNavigate(); const isSignup = useLocation().pathname.endsWith('register'); const [visible, setVisible] = useState(false); const [remember, setRemember] = useState(false)
  return <div className="auth-layout"><div className="auth-image" /><div className="auth-form"><div className="auth-form-inner"><span className="eyebrow">{isSignup ? t('auth.welcomeNew') : t('auth.welcome')}</span><h1 className="heading-1">{isSignup ? t('auth.signupTitle') : t('auth.loginTitle')}</h1><p>{isSignup ? t('auth.signupText') : t('auth.loginText')}</p><form onSubmit={(event) => { event.preventDefault(); navigate('/account') }}>{isSignup && <div className="form-field"><label>{t('auth.name')}</label><input className="input" type="text" required /></div>}<div className="form-field"><label>{t('checkout.email')}</label><input className="input" type="email" required /></div><div className="form-field"><label>{t('auth.password')}</label><div style={{ position: 'relative' }}><input className="input" type={visible ? 'text' : 'password'} required /><button type="button" className="icon-btn" style={{ position: 'absolute', insetInlineEnd: 0, top: 2 }} aria-label={visible ? t('common.close') : t('auth.password')} onClick={() => setVisible(!visible)}>{visible ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></div>{!isSignup && <div className="auth-choice"><label className="checkbox-label"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} /> {t('auth.remember')}</label><button type="button" className="text-button">{t('auth.forgot')}</button></div>}<Button variant="accent">{isSignup ? t('auth.signUp') : t('auth.signIn')}</Button></form><p className="auth-switch">{isSignup ? t('auth.already') : t('auth.newHere')} <Link className="text-link" to={isSignup ? '/auth/login' : '/auth/register'}>{isSignup ? t('auth.signIn') : t('auth.create')}</Link></p></div></div></div>
}
