import { ArrowRight, Check, Headphones, RotateCcw, ShieldCheck, Truck } from 'lucide-react'
import { motion } from 'framer-motion'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { categories, featuredProducts, newArrivals } from '@/data/products'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/Button'
import { ProductCard } from '@/components/ui/ProductCard'
import { SectionHeading } from '@/components/ui/SectionHeading'
import { Container } from '@/components/layout/Container'

const heroImages = ['photo-1600210492486-724fe5c67fb0', 'photo-1616486338812-3dadae4b4ace', 'photo-1600566753190-17f0baa2a6c3']
export function Home() { const { t } = useTranslation(); const [slide, setSlide] = useState(0); useEffect(() => { const timer = window.setInterval(() => setSlide((current) => (current + 1) % heroImages.length), 6000); return () => window.clearInterval(timer) }, []); return <>
  <section className="hero"><motion.img className="hero-image" key={slide} initial={{ opacity: .2, scale: 1.05 }} animate={{ opacity: .88, scale: 1 }} transition={{ duration: .6 }} src={`https://images.unsplash.com/${heroImages[slide]}?auto=format&fit=crop&w=1800&q=85`} alt={t('home.heroAlt')} /><div className="hero-content"><span className="eyebrow" style={{ color: '#F0B39A' }}>{t('home.eyebrow')}</span><h1 className="heading-1">{t('home.title')}</h1><p className="hero-copy">{t('home.subtitle')}</p><div className="hero-actions"><Link className="btn btn-accent" to="/shop">{t('home.shopCollection')} <ArrowRight size={17} /></Link><Link className="btn btn-outline" to="/about">{t('home.ourStory')}</Link></div><div className="hero-dots" aria-label={t('home.slides')} role="tablist">{heroImages.map((_, index) => <button key={index} className={`hero-dot ${slide === index ? 'active' : ''}`} aria-label={t('home.slide', { count: index + 1 })} onClick={() => setSlide(index)} />)}</div></div></section>
  <Container><div className="benefits"><div className="benefit"><Truck size={20} /><div><strong>{t('benefits.delivery')}</strong><span>{t('benefits.deliveryDetail')}</span></div></div><div className="benefit"><RotateCcw size={20} /><div><strong>{t('benefits.returns')}</strong><span>{t('benefits.returnsDetail')}</span></div></div><div className="benefit"><Headphones size={20} /><div><strong>{t('benefits.support')}</strong><span>{t('benefits.supportDetail')}</span></div></div><div className="benefit"><ShieldCheck size={20} /><div><strong>{t('benefits.secure')}</strong><span>{t('benefits.secureDetail')}</span></div></div></div></Container>
  <section className="section"><Container><SectionHeading eyebrow={t('home.categories')} title={t('home.categories')} link="/collections" linkLabel={t('common.viewAll')} /><div className="category-mosaic">{categories.map((category) => <Link className="category-tile" key={category.id} to={`/shop?category=${category.id}`}><img src={category.image} alt={t(`categories.${category.id}.name`, { defaultValue: category.name })} loading="lazy" /><div className="category-label"><h3>{t(`categories.${category.id}.name`, { defaultValue: category.name })}</h3><span>{t('home.categoryCount', { count: category.count })}</span></div></Link>)}</div></Container></section>
  <section className="section section-tint"><Container><SectionHeading eyebrow={t('home.selectionEyebrow')} title={t('home.featured')} description={t('home.featuredIntro')} link="/shop" linkLabel={t('common.viewAll')} /><div className="product-grid">{featuredProducts.map((product) => <ProductCard key={product.id} product={product} />)}</div></Container></section>
  <section className="editorial"><motion.img initial={{ opacity: 0, scale: 1.03 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ duration: .55 }} src="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=85" alt={t('home.editorialAlt')} loading="lazy" /><div className="editorial-copy"><span className="eyebrow" style={{ color: '#F0B39A' }}>{t('home.editorialEyebrow')}</span><h2 className="heading-2">{t('home.editorialTitle')}</h2><p>{t('home.editorialText')}</p><Link className="btn btn-outline" style={{ color: 'white', borderColor: 'white', alignSelf: 'start', marginTop: '1rem' }} to="/about">{t('home.ourStory')}</Link></div></section>
  <section className="section"><Container><SectionHeading eyebrow={t('home.newEyebrow')} title={t('home.new')} description={t('home.newIntro')} link="/new-arrivals" linkLabel={t('common.viewAll')} /><div className="product-grid">{newArrivals.map((product) => <ProductCard key={product.id} product={product} />)}</div></Container></section>
  <section className="section newsletter"><Container><Check size={22} /><h2 className="heading-2">{t('home.newsletterTitle')}</h2><p>{t('home.newsletterText')}</p><form className="newsletter-form" onSubmit={(event) => event.preventDefault()}><input className="input" type="email" placeholder={t('home.emailPlaceholder')} aria-label={t('home.emailPlaceholder')} /><Button variant="accent">{t('home.subscribe')}</Button></form></Container></section>
  </> }
