import { Heart, Star } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { products } from '@/data/products'
import { useCart } from '@/hooks/useCart'
import { useWishlist } from '@/hooks/useWishlist'
import { useTranslation } from 'react-i18next'
import { formatPrice } from '@/utils/format'
import { Button } from '@/components/ui/Button'
import { Container } from '@/components/layout/Container'
import { ProductCard } from '@/components/ui/ProductCard'
import { PageHeader } from '@/components/layout/PageHeader'

export function ProductDetails() {
  const { slug } = useParams(); const product = products.find((item) => item.slug === slug); const { t } = useTranslation(); const cart = useCart(); const wishlist = useWishlist(); const [tab, setTab] = useState('description')
  if (!product) return <PageHeader title={t('product.notFound')} />
  const name = t(`products.${product.id}.name`, { defaultValue: product.name }); const description = t(`products.${product.id}.description`, { defaultValue: product.description }); const category = t(`categories.${product.category}.name`, { defaultValue: product.categoryLabel }); const brand = t(`brands.${product.brand}`, { defaultValue: product.brand }); const related = products.filter((item) => item.category === product.category && item.id !== product.id).slice(0, 4)
  return <><section className="section"><Container><div className="breadcrumbs"><Link to="/">{t('common.home')}</Link> / <Link to="/shop">{t('nav.shop')}</Link> / {name}</div><div className="product-detail" style={{ marginTop: '2rem' }}><motion.div className="gallery" initial={{ opacity: 0, x: -18 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .45 }}><div className="gallery-main"><img src={product.image} alt={name} width="900" height="1125" /></div></motion.div><div className="detail-info"><span className="product-category">{category} · {brand}</span><h1 className="heading-1">{name}</h1><div style={{ display: 'flex', gap: '.35rem', color: 'var(--accent)' }} aria-label={t('product.ratingLabel', { rating: product.rating })}>{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={15} fill={index < Math.round(product.rating) ? 'currentColor' : 'none'} />)} <span style={{ color: 'var(--muted)', fontSize: '.8rem', marginInlineStart: '.35rem' }}>{product.reviewCount} {t('product.reviews')}</span></div><p className="detail-price price">{formatPrice(product.price)} {product.compareAt && <span className="compare" style={{ fontSize: '1rem', marginInlineStart: '.5rem' }}>{formatPrice(product.compareAt)}</span>}</p><p className="detail-description">{description}</p><span className="variant-label">{product.stock <= 5 ? t('product.lowStock', { count: product.stock }) : t('product.inStock')}</span><div className="detail-actions"><Button variant="accent" onClick={() => cart.add(product)}>{t('common.addToCart')}</Button><button className="icon-btn" style={{ border: '1px solid var(--line)', borderRadius: 'var(--radius)' }} aria-label={wishlist.has(product.id) ? t('common.removeFromWishlist') : t('common.addToWishlist')} onClick={() => wishlist.toggle(product.id)}><Heart fill={wishlist.has(product.id) ? 'currentColor' : 'none'} /></button></div><div className="detail-tabs"><div className="tab-list"><button className={`tab ${tab === 'description' ? 'active' : ''}`} onClick={() => setTab('description')}>{t('product.description')}</button><button className={`tab ${tab === 'details' ? 'active' : ''}`} onClick={() => setTab('details')}>{t('product.details')}</button><button className={`tab ${tab === 'shipping' ? 'active' : ''}`} onClick={() => setTab('shipping')}>{t('product.shipping')}</button></div><div className="tab-content">{tab === 'description' && <p>{description}</p>}{tab === 'details' && <p>{t('product.madeBy', { brand })} {t('product.care')} {t('product.updated')}</p>}{tab === 'shipping' && <p>{t('product.shippingText')}</p>}</div></div></div></div></Container></section><section className="section section-tint"><Container><h2 className="heading-2" style={{ marginBottom: '2rem' }}>{t('product.related')}</h2><div className="product-grid">{related.map((item) => <ProductCard product={item} key={item.id} />)}</div></Container></section></>
}
