import { SlidersHorizontal } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { categories, products } from '@/data/products'
import { useTranslation } from 'react-i18next'
import { Container } from '@/components/layout/Container'
import { PageHeader } from '@/components/layout/PageHeader'
import { ProductCard } from '@/components/ui/ProductCard'
import { Button } from '@/components/ui/Button'

export function Shop({ mode = 'all' }: { mode?: 'all' | 'new' }) {
  const { t } = useTranslation(); const [params, setParams] = useSearchParams(); const [category, setCategory] = useState(params.get('category') ?? 'all'); const [sort, setSort] = useState(mode === 'new' ? 'newest' : params.get('sort') ?? 'featured'); const [brand, setBrand] = useState('all'); const [filterOpen, setFilterOpen] = useState(false); const query = params.get('q')?.toLowerCase() ?? ''; const brands = [...new Set(products.map((product) => product.brand))]
  const filtered = useMemo(() => { const result = products.filter((product) => (mode !== 'new' || product.newArrival) && (category === 'all' || product.category === category) && (brand === 'all' || product.brand === brand) && (!query || `${t(`products.${product.id}.name`, { defaultValue: product.name })} ${t(`categories.${product.category}.name`, { defaultValue: product.categoryLabel })} ${t(`brands.${product.brand}`, { defaultValue: product.brand })}`.toLowerCase().includes(query))); if (sort === 'newest') return result.sort((a, b) => Number(b.newArrival) - Number(a.newArrival)); if (sort === 'price-low') return result.sort((a, b) => a.price - b.price); if (sort === 'price-high') return result.sort((a, b) => b.price - a.price); return result }, [brand, category, mode, query, sort, t])
  const updateParam = (key: string, value: string) => { const next = new URLSearchParams(params); if (value === 'all' || (key === 'sort' && value === 'featured')) next.delete(key); else next.set(key, value); setParams(next) }
  const changeCategory = (value: string) => { setCategory(value); updateParam('category', value) }
  const changeBrand = (value: string) => { setBrand(value); updateParam('brand', value) }
  const title = mode === 'new' ? t('shop.newTitle') : t('shop.title'); const subtitle = mode === 'new' ? t('shop.newSubtitle') : t('shop.subtitle')
  return <><PageHeader title={title} subtitle={subtitle} /><section className="section"><Container><div className="shop-layout"><aside className="filter-sidebar"><FilterOptions category={category} brand={brand} brands={brands} onCategoryChange={changeCategory} onBrandChange={changeBrand} t={t} /></aside><div><div className="shop-toolbar"><strong>{t('shop.showing', { count: filtered.length })}</strong><div className="shop-controls"><Button variant="ghost" className="mobile-filter" onClick={() => setFilterOpen((value) => !value)} aria-expanded={filterOpen}><SlidersHorizontal size={16} /> {t('shop.filter')}</Button><select className="sort-select" aria-label={t('shop.sort')} value={sort} onChange={(event) => { setSort(event.target.value); updateParam('sort', event.target.value) }}><option value="featured">{t('shop.featured')}</option><option value="newest">{t('shop.newest')}</option><option value="price-low">{t('shop.priceLow')}</option><option value="price-high">{t('shop.priceHigh')}</option></select></div></div>{filterOpen && <div className="mobile-filter-panel"><FilterOptions category={category} brand={brand} brands={brands} onCategoryChange={changeCategory} onBrandChange={changeBrand} t={t} /></div>}{filtered.length ? <div className="product-grid">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="empty-state"><h2>{t('shop.empty')}</h2><button className="text-link" onClick={() => { setCategory('all'); setBrand('all'); updateParam('category', 'all'); updateParam('brand', 'all') }}>{t('shop.reset')}</button></div>}</div></div></Container></section></>
}

function FilterOptions({ category, brand, brands, onCategoryChange, onBrandChange, t }: { category: string; brand: string; brands: string[]; onCategoryChange: (value: string) => void; onBrandChange: (value: string) => void; t: (key: string, options?: { defaultValue?: string }) => string }) {
  return <div className="filter-options"><div className="filter-group"><h3>{t('shop.category')}</h3><select className="mobile-filter-select" value={category} onChange={(event) => onCategoryChange(event.target.value)} aria-label={t('shop.category')}><option value="all">{t('shop.all')}</option>{categories.map((item) => <option value={item.id} key={item.id}>{t(`categories.${item.id}.name`, { defaultValue: item.name })}</option>)}</select><div className="desktop-filter-options"><label className="filter-option"><input type="radio" checked={category === 'all'} onChange={() => onCategoryChange('all')} /> {t('shop.all')}</label>{categories.map((item) => <label className="filter-option" key={item.id}><input type="radio" checked={category === item.id} onChange={() => onCategoryChange(item.id)} /> {t(`categories.${item.id}.name`, { defaultValue: item.name })}</label>)}</div></div><div className="filter-group"><h3>{t('shop.brand')}</h3><select className="mobile-filter-select" value={brand} onChange={(event) => onBrandChange(event.target.value)} aria-label={t('shop.brand')}><option value="all">{t('shop.allBrands')}</option>{brands.map((item) => <option value={item} key={item}>{t(`brands.${item}`, { defaultValue: item })}</option>)}</select><div className="desktop-filter-options"><label className="filter-option"><input type="radio" checked={brand === 'all'} onChange={() => onBrandChange('all')} /> {t('shop.allBrands')}</label>{brands.map((item) => <label className="filter-option" key={item}><input type="radio" checked={brand === item} onChange={() => onBrandChange(item)} /> {t(`brands.${item}`, { defaultValue: item })}</label>)}</div></div></div>
}
